POST http://localhost:3001/api/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRyaXBsZXkiLCJpZCI6IjVlMzcwOGRjZTgzNjczNDdlNGU1YjI4MCIsImlhdCI6MTU4MDg2NzY1MCwiZXhwIjoxNTgwODcxMjUwfQ.nTs9b943PFtT6zQHdZMWwq1mfAk7umE59hyCPVSUuBQ
content-type: application/json

{
    "categoryName": "Example Primary Category", 
    "description": "This is a baseline category",
    "isMajor": "true"
}